# Q1: Fun with arrays

In [2]:

import numpy as np

#parte 1

a = np.arange(1,16).reshape(5,3, order = 'F') #vettore1
print('a : ')
print(a)

b = a[[1,3],:] #vettore 2
print('b : ')
print (b)

def due_d(righe, colonne) : 
    zero = np.zeros((righe, colonne), dtype=int).reshape(righe,colonne)
    zero[0,:] = 1
    zero[righe -1 , :]=1 
    zero[:,0] = 1
    zero[:, colonne-1] = 1

    return zero

righe = int(input('num righe: '))
colonne = int(input('num colonne: '))
print('c : ')
print(due_d(righe, colonne))



a : 
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
b : 
[[ 2  7 12]
 [ 4  9 14]]


num righe:  6
num colonne:  8


c : 
[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


# Q2: Histograms

In [51]:
import numpy as np
import requests


url = "https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt"
filename = "sample.txt"

response = requests.get(url)
with open(filename, 'wb') as f:
    f.write(response.content)


x, y = np.loadtxt(filename, unpack=True)    #x e l'indice mentre y è il valore effettivo 

counts, bin_edges = np.histogram(y, bins=10)


for i in range(len(counts)):
    bin_center = (bin_edges[i] + bin_edges[i+1]) / 2
    print(f"Bin center: {bin_center:.2f}, Count: {counts[i]}")


Bin center: -27.13, Count: 3
Bin center: -20.21, Count: 4
Bin center: -13.29, Count: 9
Bin center: -6.37, Count: 22
Bin center: 0.54, Count: 22
Bin center: 7.46, Count: 22
Bin center: 14.38, Count: 9
Bin center: 21.30, Count: 7
Bin center: 28.22, Count: 1
Bin center: 35.14, Count: 1


# Q3: Are you faster than numpy? No

In [8]:
import numpy as np
import time

def dev(a): #funzione che calcola la dev standard
    a_med = sum(a)/len(a)
    
    
    b = 0
    for i in range(len(a)):
        b += ((a[i]-a_med)**2)/len(a)
    
    return np.sqrt(b)


a = np.arange(1000) #array di test
print('la deviazione standard calcolata dalla funzione dev è : ')
t0 = time.time()
print(dev(a))
t1 = time.time()
print('la deviazione standard calcolata da py è : ')
t2 = time.time()
print(np.std(a))
t3 = time.time()
print("tempo impiegato dalla funzione: {} s".format(t1-t0))
print("tempo impiegato da py: {} s".format(t3-t2))

la deviazione standard calcolata dalla funzione dev è : 
288.6749902572095
la deviazione standard calcolata da py è : 
288.6749902572095
tempo impiegato dalla funzione: 0.001013040542602539 s
tempo impiegato da py: 0.00039196014404296875 s
